name: "Action B"
description: "my second action"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who am I?"
    required: true
    default: "Scott long"

runs:
  using: "docker"
  image: "dockerFile"

branding:
  icon: "mic"
  color: "purple"
