name: Action b actions
on:
  push:
    branches:
      - "feature/action-b"
jobs:
  action_b_build:
   name: action-b
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: user action b
        uses: ./action-b
        with:
          MY_NAME: "Big tea"
    
