name: Action b actions
on:
  push:
    branches:
      - "feature/action-b"
jobs:
  action_b_build:
    name: build action-b ref
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'feature/action-b'
      - name: user action b
        uses: ./action-b
        with:
          MY_NAME: "Big tea"
    
