name: Workflow for the actions demo
on: push

jobs:
  build:
    name: run the jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'feature/action-demo'
          
      - uses: ./action-a
        with:
          MY_NAME: "the Name"
