name: Workflow for the actions demo
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - uses: ./actions-a/actions.yml
        with:
          MY_NAME: "the Name"
